before_script:

env:
  - DB_HOST="127.0.0.1" DB_PORT=3306 DB_USER="root" DB_PASS="" DB_NAME="session_test"

language: node_js
node_js:
  - "6"

before_install: npm install -g grunt-cli
install: npm install
